import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "@afs/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
        <Toaster
          theme="dark" // or "dark", "system"
          position="top-right"
          toastOptions={{
            style: {
              background: "hsl(var(--accent))",
              color: "hsl(var(--card-foreground))",
              border: "1px solid hsl(var(--border))",
              backdropFilter: "blur(4px)",
            },
          }}
        />
      </body>
    </html>
  );
}
