"use client";
import { type Metadata } from "next";
import { ThemeProvider } from "@afs/components/ui/ThemeProvider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function Providers({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="light"
      enableSystem
      disableTransitionOnChange
    >
      <ClerkProvider>
        <header className="flex justify-end items-center p-4 gap-4 h-16">
          <SignedOut>
            {path !== "/auth/sign-in" && (
              <SignInButton>
                <button className="bg-background border border-accent px-2 py-1 rounded-md cursor-pointer">
                  Sign In
                </button>
              </SignInButton>
            )}
            {path !== "/auth/sign-up" && (
              <SignUpButton>
                <button className="bg-background border border-accent px-2 py-1 rounded-md cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            )}
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
        </header>
        {children}
      </ClerkProvider>
    </ThemeProvider>
  );
}
