"use client";
import { type Metadata } from "next";
import { ThemeProvider } from "@afs/components/ui/ThemeProvider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { usePathname } from "next/navigation";
import { Button } from "@afs/components/ui/button";
import Link from "next/link";
import { Toaster } from "@afs/components/ui/sonner";
import Navbar from "@afs/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function Providers({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const path = usePathname();

  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="light"
      enableSystem
      disableTransitionOnChange
    >
      <ClerkProvider>
        <header className="flex justify-end items-center p-4 gap-4 h-16">
          {/* <SignedOut>
            {path !== "/auth/sign-in" && (
              <Button className="px-6">
                <Link href="/auth/sign-in">Sign n</Link>
              </Button>
            )}
            {path !== "/auth/sign-up" && (
              <Button className="px-6">
                <Link href="/auth/sign-up">Sign Up</Link>
              </Button>
            )}
          </SignedOut> */}
          <SignedIn>
            <UserButton />
          </SignedIn>
        </header>
        {children}
      </ClerkProvider>
    </ThemeProvider>
  );
}
